// @ts-check
import { createConfigForNuxt } from '@nuxt/eslint-config/flat'
import vuejsAccessibility from 'eslint-plugin-vuejs-accessibility'

export default createConfigForNuxt({
  features: {
    tooling: true,
    stylistic: false, // Prettier handles formatting
  },
  dirs: {
    src: ['./app'],
  },
})
  // C13: accessibility as a LINT gate, not only an E2E one.
  //
  // axe runs against rendered pages, so it only ever sees the states a test
  // happens to drive. A missing alt on an error branch nobody exercised is
  // invisible to it — and this project has just shipped a WCAG 2.4.2 violation
  // on its most important screen precisely because axe was never pointed at it.
  //
  // The linter reads every template unconditionally, so the two catch different
  // things and neither replaces the other.
  .append(vuejsAccessibility.configs['flat/recommended'])
  .append({
    rules: {
      // Enforce no unused vars (D27 strict mode).
      //
      // The base rule is switched OFF in favour of the TypeScript one: they
      // both fire on the same code, but only the TS rule understands the
      // `_`-prefix convention for deliberately-unused arguments. Leaving both
      // on means a signature that must keep a parameter for arity — a stub
      // handler, a callback shape — cannot be silenced by any means except
      // deleting the parameter and breaking the contract.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  })
  // Vendored shadcn-vue primitives. `label-has-for` cannot see through a
  // component boundary: these render Reka UI's <Label>, which wires for/id via
  // context at runtime, so the association it is asking for genuinely exists —
  // axe proves it on the rendered page, which is the check that counts.
  //
  // Scoped to this directory rather than switched off globally, and for a
  // second reason beyond the false positive: these files are regenerated by
  // `shadcn-vue add`, so any edit here is lost on the next component install.
  // A hand-fixed vendored file is a fix with an expiry date.
  .append({
    files: ['app/components/ui/**/*.vue'],
    rules: {
      'vuejs-accessibility/label-has-for': 'off',
    },
  })
  // Same false-positive category as above, one file over: FieldLabel wraps
  // Reka UI's Label, which forwards `for` as a genuine HTML attribute onto
  // whatever it labels — but the plugin cannot trace a `for`/`id` pair
  // through the Field -> FieldLabel -> Select -> SelectTrigger component
  // chain, so it reports the pair as unassociated even though the rendered
  // <label for> -> <button id> association is real. Verified by the existing
  // Playwright axe check at the device-check screen (interview-flow.spec.ts,
  // zero WCAG 2.1 AA violations, both engines) rather than switched off blind.
  .append({
    files: ['app/components/DeviceCheck.client.vue'],
    rules: {
      'vuejs-accessibility/form-control-has-label': 'off',
    },
  })
  // GENERATED FILES ARE NOT SOURCE.
  //
  // `types/api.ts` is produced by `openapi-typescript` from `openapi.json`, and
  // `scripts/check-client-drift.sh` regenerates it in CI and diffs byte for
  // byte. Any tool that rewrites it makes a correctly-synced client report as
  // drifted — `eslint --fix` runs on it through lint-staged, a rule reflows one
  // JSDoc line by a single `*`, and the `Client drift check` step fails.
  //
  // `.prettierignore` already covers both files and prettier honours it even
  // for explicitly-passed paths, so prettier was never the culprit. ESLint had
  // no matching entry at all — this is that entry. Same fix as the backoffice,
  // where this failed the v0.24.0 release merge-back.
  .append({
    ignores: ['types/api.ts', 'openapi.json'],
  })
