// @ts-check
import { createConfigForNuxt } from '@nuxt/eslint-config/flat'
import vuejsAccessibility from 'eslint-plugin-vuejs-accessibility'

export default createConfigForNuxt({
  features: {
    tooling: true,
    stylistic: false, // Prettier handles formatting
  },
  dirs: {
    src: ['./app'],
  },
})
  // C13: accessibility as a LINT gate, not only an E2E one.
  //
  // axe runs against rendered pages, so it only ever sees the states a test
  // happens to drive. A missing alt on an error branch nobody exercised is
  // invisible to it — and this project has just shipped a WCAG 2.4.2 violation
  // on its most important screen precisely because axe was never pointed at it.
  //
  // The linter reads every template unconditionally, so the two catch different
  // things and neither replaces the other.
  .append(vuejsAccessibility.configs['flat/recommended'])
  .append({
    rules: {
      // Enforce no unused vars (D27 strict mode).
      //
      // The base rule is switched OFF in favour of the TypeScript one: they
      // both fire on the same code, but only the TS rule understands the
      // `_`-prefix convention for deliberately-unused arguments. Leaving both
      // on means a signature that must keep a parameter for arity — a stub
      // handler, a callback shape — cannot be silenced by any means except
      // deleting the parameter and breaking the contract.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  })
  // Vendored shadcn-vue primitives. `label-has-for` cannot see through a
  // component boundary: these render Reka UI's <Label>, which wires for/id via
  // context at runtime, so the association it is asking for genuinely exists —
  // axe proves it on the rendered page, which is the check that counts.
  //
  // Scoped to this directory rather than switched off globally, and for a
  // second reason beyond the false positive: these files are regenerated by
  // `shadcn-vue add`, so any edit here is lost on the next component install.
  // A hand-fixed vendored file is a fix with an expiry date.
  .append({
    files: ['app/components/ui/**/*.vue'],
    rules: {
      'vuejs-accessibility/label-has-for': 'off',
    },
  })
